//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAN_Witel_Karawang.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TechInfo
    {
        public int TechInfoID { get; set; }
        public string SID { get; set; }
        public string TQ { get; set; }
        public string AO { get; set; }
        [Display(Name = "Nama")]
        public string Name { get; set; }
        [Display(Name = "Tgl Order di Tenoss")]
        public Nullable<System.DateTime> OrderTime { get; set; }
        [Display(Name = "Alamat")]
        public string Address { get; set; }
        [Display(Name = "Komentar di TeNOSS")]
        public string TeNOSScomment { get; set; }
        public string PIC { get; set; }
        [Display(Name = "Kode Area")]
        public string AreaCode { get; set; }
        public string Metro { get; set; }
        public string GPON { get; set; }
        public string SN { get; set; }
        public string VLAN { get; set; }
        [Display(Name = "Tgl Perintah Survey")]
        public Nullable<System.DateTime> SurveyTime { get; set; }
        [Display(Name = "Tagging Pelanggan")]
        public string CustTag { get; set; }
        [Display(Name = "Teknisi Survey")]
        public string SurveyTech { get; set; }
        [Display(Name = "Tagging ODP")]
        public string ODPTag { get; set; }
        [Display(Name = "Tgl Perintah PT-1")]
        public Nullable<System.DateTime> PT1Com { get; set; }
        [Display(Name = "Tgl Selesai PT-1")]
        public Nullable<System.DateTime> PT1End { get; set; }
        [Display(Name = "Teknisi PT-1")]
        public string PT1Tech { get; set; }
        [Display(Name = "Tgl Perintah JT")]
        public Nullable<System.DateTime> JTTime { get; set; }
        [Display(Name = "Tgl JT Selesai")]
        public Nullable<System.DateTime> JTEnd { get; set; }
        [Display(Name = "Komentar")]
        public string comment { get; set; }
        [Display(Name = "Tgl Closed")]
        public Nullable<System.DateTime> ClosedTime { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
    }
}
